# Generated by Django 5.0.6 on 2024-05-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('pos', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sample', models.CharField(blank=True, max_length=100)),
                ('primers', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
